import type {Metadata} from "next";

import "./globals.css";
import Link from "next/link";

export const metadata: Metadata = {
  title: "MercaLibre",
  description: "Generated by appncy",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="es">
      <body className="bg-gray-100">
        <header className="flex h-min w-full justify-center bg-yellow-200 py-3 text-black">
          <Link className="pr-5 text-3xl font-bold" href="/">
            MercaLibre
          </Link>
          <form action="/items" className="flex">
            <input
              className="w-[600px] pl-3"
              name="search"
              placeholder="Iphone, Macbook, Laptops, etc..."
              type="text"
            />
            <button className="bg-gray-200 px-2 py-1" type="submit">
              Buscar
            </button>
          </form>
        </header>
        {children}
      </body>
    </html>
  );
}
